// Generated by tools/build_card_pages.py. Cards that have their own shareable page.
window.GC01_CARD_PAGES = ["articuno", "bulbasaur", "charizard-holo-1st-ed", "charizard-v", "eevee-ex", "espeon-ex", "flareon-ex", "jolteon-ex", "leafeon-ex", "mega-dragonite-ex", "mega-gengar-ex", "mega-gengar-ex-ascended", "mega-venusaur-ex", "mewtwo-ex", "ninetales", "pidgeot-ex", "pikachu-ex"];
window.gc01ProductUrl = function (id) {
  return window.GC01_CARD_PAGES.indexOf(id) !== -1 ? "card-" + id + ".html" : "product.html?id=" + encodeURIComponent(id);
};
