#!/usr/bin/env python3
"""Build the site's generated, search-optimised pages from products.js.

WhatsApp, Instagram, Facebook and search engines read a page's HTML and <meta>
tags, so everything that should be found or shared is written out as real HTML
here rather than filled in by JavaScript. For each run this writes:

  card-<id>.html            one page per card, built from product.html, with a
                            unique SEO title and description, "About this card"
                            copy, breadcrumbs, internal links and Product data
  images/share/<id>.jpg     a 1200x630 link-preview image per card
  <category>.html           landing pages (PSA graded, PSA 10, Japanese, eras,
                            Pokémon...) for every category with enough stock,
                            configured in seo/categories.json
  pokemon-tcg-sets.html     every Pokémon TCG era and set, from seo/sets.json
  card-pages.js             the list of card pages, so the site links to them
  sitemap.xml               every indexable page, with card photos
  google-merchant-feed.xml  in-stock cards for free Google Shopping listings
It also refreshes the "shop by" links on the home page and in every footer
(between <!-- seo:... --> markers). Product names and checkout are never touched.

Run after changing products.js, product.html, seo/*.json or a card photo:
    python3 tools/build_card_pages.py
then check the result with:
    python3 tools/seo_audit.py
The "Card share pages" GitHub Action runs both on every relevant push to main.
Needs node (to read products.js) and Pillow.
"""
import json
import os
import re
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFilter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import seo_lib as L  # noqa: E402

ROOT = L.ROOT
SITE = L.SITE
STORE = L.STORE
esc = L.esc
SHIPPING_GBP = "10.00"
GENERATED_MARK = "<!-- Generated by tools/build_card_pages.py"
GUIDE_FILE = "pokemon-tcg-sets.html"

# Legal trader details shown in every footer (UK Consumer Contracts Regulations).
# If the business becomes a limited company, replace with the company name,
# registration number and registered office; add the VAT number if registered.
TRADER = ("Graded Cards 01 is a trading name of Razwaan Ullah, sole trader, 24 Crystal Drive, "
          "Peterborough, PE2 9RJ, United Kingdom. Not VAT registered.")

# Public, indexable hand-written pages for the sitemap. Generated pages are added
# automatically. sealed.html and raw-cards.html are "coming soon" and noindex; add
# them here (and remove their robots meta tag) once they have products.
STATIC_PAGES = ["", "about.html", "faq.html", "shipping.html", "contact.html",
                "terms.html", "privacy.html", "notify.html"]

SHARE_DIR = os.path.join(ROOT, "images", "share")
W, H = 1200, 630


def load_products():
    js = (
        "const fs=require('fs');"
        "eval(fs.readFileSync(process.argv[1],'utf8')+';globalThis.__P=PRODUCTS');"
        "process.stdout.write(JSON.stringify(globalThis.__P));"
    )
    out = subprocess.check_output(["node", "-e", js, os.path.join(ROOT, "products.js")])
    return json.loads(out)


def read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


def write(rel, text):
    path = os.path.join(ROOT, rel)
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != text:
        with open(path, "w", encoding="utf-8") as f:
            f.write(text)


def ld_script(data):
    return '  <script type="application/ld+json">' + json.dumps(data, ensure_ascii=False).replace("</", "<\\/") + "</script>\n"


# ---------------------------------------------------------------- images

def share_image(p):
    """Card photo centred on the site's dark background with a soft blue glow."""
    card = Image.open(os.path.join(ROOT, p["image"])).convert("RGB")
    bg = Image.new("RGB", (W, H), (22, 21, 19))
    glow = Image.new("L", (W, H), 0)
    ImageDraw.Draw(glow).ellipse((W // 2 - 420, -120, W // 2 + 420, H + 120), fill=110)
    glow = glow.filter(ImageFilter.GaussianBlur(120))
    bg.paste(Image.new("RGB", (W, H), (52, 84, 214)), (0, 0), glow)
    ch = H - 60
    cw = round(card.width * ch / card.height)
    card = card.resize((cw, ch), Image.LANCZOS)
    shadow = Image.new("L", (W, H), 0)
    x, y = (W - cw) // 2, 30
    ImageDraw.Draw(shadow).rectangle((x + 10, y + 24, x + cw + 10, y + ch + 24), fill=170)
    shadow = shadow.filter(ImageFilter.GaussianBlur(22))
    bg.paste(Image.new("RGB", (W, H), (0, 0, 0)), (0, 0), shadow)
    bg.paste(card, (x, y))
    logo_path = os.path.join(ROOT, "images", "logo-mark.png")
    if os.path.exists(logo_path):
        logo = Image.open(logo_path).convert("RGBA").resize((88, 88), Image.LANCZOS)
        bg.paste(logo, (W - 88 - 36, H - 88 - 36), logo)
    os.makedirs(SHARE_DIR, exist_ok=True)
    bg.save(os.path.join(SHARE_DIR, f"{p['id']}.jpg"), "JPEG", quality=84, optimize=True, progressive=True)
    return f"images/share/{p['id']}.jpg"


# ---------------------------------------------------------------- head helpers

def set_meta(doc, attr, key, value):
    """Replace the content of <meta {attr}="{key}" ...>, or add it before </head>."""
    pattern = re.compile(r'<meta %s="%s" content="[^"]*"\s*/?>' % (attr, re.escape(key)))
    tag = f'<meta {attr}="{key}" content="{esc(value)}" />'
    if pattern.search(doc):
        return pattern.sub(lambda _m: tag, doc, count=1)
    return doc.replace("</head>", f"  {tag}\n</head>", 1)


def set_head(doc, title, description, url, image_url, og_type="website", image_size=None):
    doc = re.sub(r"<title>.*?</title>", lambda _m: f"<title>{esc(title)}</title>", doc, count=1)
    doc = re.sub(r'\s*<link rel="canonical"[^>]*>', "", doc)
    doc = re.sub(r'\s*<meta name="robots"[^>]*>', "", doc)
    og_title = title.replace(f" | {STORE}", "")
    for attr, key, value in [
        ("name", "description", description),
        ("property", "og:title", og_title),
        ("property", "og:description", description),
        ("property", "og:type", og_type),
        ("property", "og:site_name", STORE),
        ("property", "og:url", url),
        ("property", "og:image", image_url),
        ("name", "twitter:card", "summary_large_image"),
        ("name", "twitter:title", og_title),
        ("name", "twitter:description", description),
        ("name", "twitter:image", image_url),
    ]:
        doc = set_meta(doc, attr, key, value)
    if image_size:
        doc = set_meta(doc, "property", "og:image:width", str(image_size[0]))
        doc = set_meta(doc, "property", "og:image:height", str(image_size[1]))
    return doc.replace("</head>", f'  <link rel="canonical" href="{url}" />\n</head>', 1)


def breadcrumb_ld(items):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": n + 1, "name": name, "item": url}
            for n, (name, url) in enumerate(items)
        ],
    }


# ---------------------------------------------------------------- card pages

def primary_category(product, pages):
    """The page a card's breadcrumb points to: its era, else its grader."""
    for kind, key in (("era", None), ("fixed", "psa"), ("fixed", "ace")):
        for pg in pages:
            if pg["kind"] == kind and (key is None or pg["id"] == key) and any(c["id"] == product["id"] for c in pg["cards"]):
                return pg
    return None


def card_page(template, p, i, image_rel, registry, pages):
    url = f"{SITE}/card-{p['id']}.html"
    title = L.seo_title(p, i)
    desc = L.seo_description(p, i)
    doc = set_head(template, title, desc, url, f"{SITE}/{image_rel}", og_type="product", image_size=(W, H))
    for attr, key, value in [
        ("property", "og:image:alt", f"{p['name']} {p['grade']} graded Pokémon card"),
        ("property", "product:price:amount", f"{p['price']:.2f}"),
        ("property", "product:price:currency", p.get("currency", "GBP")),
        ("property", "product:availability", "out of stock" if p.get("sold") else "in stock"),
        ("property", "product:condition", "used"),
    ]:
        doc = set_meta(doc, attr, key, value)

    era_label = registry.era_label(i["era"]) if i["era"] else None
    props = [("Grading company", i["company"]), ("Grade", f"{i['grade_num']} {p['gradeLabel']}"),
             ("Cert number", str(p["certNumber"])), ("Set", i["set_display"]), ("Card number", p["cardNumber"]),
             ("Language", i["lang_name"])]
    if era_label:
        props.append(("Era", era_label))
    if i["rarity"]:
        props.append(("Rarity", i["rarity"]))
    product_ld = {
        "@context": "https://schema.org",
        "@type": "Product",
        "name": f"{p['name']} {p['grade']} {p['gradeLabel']}",
        "description": desc,
        "image": [f"{SITE}/{p['image']}", f"{SITE}/{p['image'].replace('images/cards/', 'images/cards-full/')}"],
        "sku": str(p["certNumber"]),
        "brand": {"@type": "Brand", "name": "Pokémon"},
        "category": "Collectible Trading Cards",
        "url": url,
        "additionalProperty": [{"@type": "PropertyValue", "name": k, "value": v} for k, v in props],
        "offers": {
            "@type": "Offer",
            "url": url,
            "priceCurrency": p.get("currency", "GBP"),
            "price": f"{p['price']:.2f}",
            "availability": "https://schema.org/SoldOut" if p.get("sold") else "https://schema.org/InStock",
            "itemCondition": "https://schema.org/UsedCondition",
            "seller": {"@type": "Organization", "name": STORE, "url": SITE + "/"},
            "shippingDetails": {
                "@type": "OfferShippingDetails",
                "shippingRate": {"@type": "MonetaryAmount", "value": SHIPPING_GBP, "currency": "GBP"},
                "shippingDestination": {"@type": "DefinedRegion", "addressCountry": "GB"},
            },
            "hasMerchantReturnPolicy": {
                "@type": "MerchantReturnPolicy",
                "applicableCountry": "GB",
                "returnPolicyCategory": "https://schema.org/MerchantReturnFiniteReturnWindow",
                "merchantReturnDays": 14,
                "returnMethod": "https://schema.org/ReturnByMail",
                "returnFees": "https://schema.org/ReturnFeesCustomerResponsibility",
                "merchantReturnLink": SITE + "/shipping.html",
            },
        },
    }
    parent = primary_category(p, pages)
    crumbs = [("Graded Pokémon Cards", SITE + "/")]
    if parent:
        crumbs.append((parent["h1"], f"{SITE}/{parent['file']}"))
    crumbs.append((p["name"], url))
    doc = doc.replace("</head>", ld_script(product_ld) + ld_script(breadcrumb_ld(crumbs)) + "</head>", 1)

    # Visible content in the HTML itself (product.js re-renders the same values).
    crumb_html = '<a href="index.html#shop">Shop</a>'
    if parent:
        crumb_html += f' / <a href="{parent["file"]}">{esc(parent["h1"])}</a>'
    crumb_html += f" / <span>{esc(p['name'])}</span>"
    alt = f"{p['name']} {p['grade']} {p['gradeLabel']} graded Pokémon card, {p['set']} #{p['cardNumber']}"
    webp = p["image"].rsplit(".", 1)[0] + ".webp"
    replacements = [
        ('<p class="pdp-breadcrumb" id="pdp-breadcrumb"><a href="index.html#shop">Shop</a></p>',
         f'<p class="pdp-breadcrumb" id="pdp-breadcrumb">{crumb_html}</p>'),
        ('<section class="pdp container" id="pdp-loaded" hidden>', '<section class="pdp container" id="pdp-loaded">'),
        ("        <!-- picture, grade badge, and zoom button injected by product.js -->",
         f'        <picture><source srcset="{esc(webp)}" type="image/webp"><img src="{esc(p["image"])}" alt="{esc(alt)}" width="900" height="1440"></picture>\n'
         f'        <span class="grade-badge">{esc(p["grade"])} {esc(p["gradeLabel"])}</span>'),
        ('<h1 class="pdp-title" id="pdp-product-title"></h1>', f'<h1 class="pdp-title" id="pdp-product-title">{esc(p["name"])}</h1>'),
        ('<p class="pdp-meta" id="pdp-product-meta"></p>', f'<p class="pdp-meta" id="pdp-product-meta">{esc(p["set"])} · #{esc(p["cardNumber"])}</p>'),
        ('<p class="pdp-cert" id="pdp-product-cert"></p>',
         f'<p class="pdp-cert" id="pdp-product-cert">{esc(i["company"])} cert #{esc(p["certNumber"])} · {esc(p["grade"])} {esc(p["gradeLabel"])}</p>'),
        ('<p class="pdp-price" id="pdp-product-price"></p>', f'<p class="pdp-price" id="pdp-product-price">{esc(L.price_text(p))}</p>'),
        ('<section class="pdp-about container" id="pdp-about" aria-labelledby="pdp-about-heading" hidden></section>',
         '<section class="pdp-about container" id="pdp-about" aria-labelledby="pdp-about-heading">'
         + L.about_html(p, i, registry, L.category_links_for(p, i, pages)) + "    </section>"),
    ]
    for old, new in replacements:
        if old not in doc:
            sys.exit(f"product.html changed shape ({old[:50]}...); update tools/build_card_pages.py")
        doc = doc.replace(old, new, 1)
    # The "card not found" block (and its second <h1>) only matters on product.html.
    doc = re.sub(r'\s*<section class="pdp-notfound container" id="pdp-notfound" hidden>[\s\S]*?</section>', "", doc, count=1)

    marker = '<script src="product.js" defer></script>'
    doc = doc.replace(marker, f'<script>window.GC01_PRODUCT_ID = {json.dumps(p["id"])};</script>\n  {marker}', 1)
    return f"{GENERATED_MARK} from product.html. Edit product.html or products.js, not this file. -->\n" + doc


# ---------------------------------------------------------------- shell pages

def shell_parts():
    """Header and footer shared with the rest of the site, taken from about.html."""
    doc = read("about.html")
    head_end = doc.index("<main id=\"main\">")
    foot_start = doc.index('    <footer class="site-footer')
    return doc[:head_end], doc[foot_start:]


def card_tile(p, i):
    href = f"card-{p['id']}.html"
    alt = f"{p['name']} {p['grade']} {p['gradeLabel']} graded Pokémon card, {p['set']} #{p['cardNumber']}"
    webp = p["image"].rsplit(".", 1)[0] + ".webp"
    sold_badge = '\n            <span class="sold-badge">Sold</span>' if p.get("sold") else ""
    action = ('<span class="btn-outline btn-disabled btn-block">Sold out</span>' if p.get("sold")
              else f'<a class="btn-gold btn-block" href="{href}">View card</a>')
    return f"""        <article class="product-card" role="listitem">
          <div class="product-media">
            <a class="product-media-link" href="{href}">
              <picture><source srcset="{esc(webp)}" type="image/webp"><img src="{esc(p['image'])}" alt="{esc(alt)}" loading="lazy" width="900" height="1440"></picture>
            </a>
            <span class="grade-badge">{esc(p['grade'])} {esc(p['gradeLabel'])}</span>{sold_badge}
          </div>
          <div class="product-body">
            <h3 class="product-title"><a class="product-title-link" href="{href}">{esc(p['name'])}</a></h3>
            <p class="product-meta">{esc(p['set'])} · #{esc(p['cardNumber'])}</p>
            <p class="product-cert">{esc(i['company'])} cert #{esc(p['certNumber'])}</p>
            <div class="product-footer"><span class="price">{esc(L.price_text(p))}</span></div>
            {action}
          </div>
        </article>"""


def category_page(page, infos, pages):
    top, bottom = shell_parts()
    url = f"{SITE}/{page['file']}"
    lead = next((c for c in page["cards"] if not c.get("sold")), page["cards"][0])
    doc = set_head(top, page["title"], page["description"], url, f"{SITE}/images/share/{lead['id']}.jpg",
                   image_size=(W, H))
    items = [{"@type": "ListItem", "position": n + 1, "url": f"{SITE}/card-{c['id']}.html", "name": c["name"]}
             for n, c in enumerate(page["cards"])]
    collection = {
        "@context": "https://schema.org",
        "@type": "CollectionPage",
        "name": page["h1"],
        "description": page["description"],
        "url": url,
        "inLanguage": "en-GB",
        "isPartOf": {"@type": "WebSite", "name": STORE, "url": SITE + "/"},
        "mainEntity": {"@type": "ItemList", "numberOfItems": len(items), "itemListElement": items},
    }
    doc = doc.replace("</head>", ld_script(collection)
                      + ld_script(breadcrumb_ld([("Graded Pokémon Cards", SITE + "/"), (page["h1"], url)])) + "</head>", 1)
    tiles = "\n".join(card_tile(c, infos[c["id"]]) for c in page["cards"])
    about = "\n".join(f"      <p>{x}</p>" for x in page["about"])
    others = [pg for pg in pages if pg["file"] != page["file"]]
    related = "\n".join(f'        <li><a href="{pg["file"]}">{esc(pg["link_text"][0].upper() + pg["link_text"][1:])}</a></li>' for pg in others)
    main = f"""<main id="main">
    <div class="container">
      <p class="pdp-breadcrumb"><a href="index.html">Home</a> / <span>{esc(page['h1'])}</span></p>
    </div>
    <section class="page-hero category-hero">
      <h1>{esc(page['h1'])}</h1>
      <p>{esc(page['lede'])}</p>
    </section>

    <section class="section container" aria-label="Cards">
      <div class="product-grid" role="list">
{tiles}
      </div>
    </section>

    <section class="prose category-about" aria-labelledby="category-about-heading">
      <h2 id="category-about-heading">{esc(page['about_heading'])}</h2>
{about}
    </section>

    <section class="prose category-related" aria-labelledby="category-related-heading">
      <h2 id="category-related-heading">More graded Pokémon cards</h2>
      <ul class="browse-list">
{related}
        <li><a href="{GUIDE_FILE}">Pokémon TCG sets in order</a></li>
      </ul>
    </section>

"""
    return f"{GENERATED_MARK}: category page from seo/categories.json. Edit that file, not this one. -->\n" + doc + main + bottom


def guide_page(registry, products, infos, pages):
    top, bottom = shell_parts()
    url = f"{SITE}/{GUIDE_FILE}"
    newest_year = max(s["year"] for e in registry.eras for s in e["sets"])
    newest = [s["name"] for e in registry.eras for s in e["sets"] if s["year"] == newest_year][-1]
    en_count = sum(len(e["sets"]) for e in registry.eras)
    title = f"Pokémon TCG Sets in Order (1999–{newest_year}) | {STORE}"
    desc = L.fit_description(
        f"All {en_count} English Pokémon TCG sets in release order, from Base Set to {newest} ({newest_year}), "
        f"grouped by era, with the graded cards we have in stock from each.")
    doc = set_head(top, title, desc, url, f"{SITE}/images/og-image.jpg")
    webpage = {"@context": "https://schema.org", "@type": "WebPage", "name": "Pokémon TCG Sets in Order",
               "description": desc, "url": url, "inLanguage": "en-GB",
               "isPartOf": {"@type": "WebSite", "name": STORE, "url": SITE + "/"}}
    doc = doc.replace("</head>", ld_script(webpage) + ld_script(breadcrumb_ld(
        [("Graded Pokémon Cards", SITE + "/"), ("Pokémon TCG Sets in Order", url)])) + "</head>", 1)
    era_pages = {pg["id"]: pg for pg in pages if pg["kind"] == "era"}
    toc = "\n".join(f'          <li><a href="#era-{e["id"]}">{esc(e["name"])}</a> <span class="set-year">{esc(e["years"])}</span></li>'
                    for e in registry.eras)
    sections = []
    for e in registry.eras:
        sets = "\n".join(
            f'          <li>{esc(s["name"])} <span class="set-year">{s["year"]}</span>'
            + (f' <span class="set-kind">{esc(s["kind"])}</span>' if s.get("kind") else "") + "</li>"
            for s in e["sets"])
        jp = ""
        if e.get("japanese_sets"):
            jp_items = "\n".join(f'          <li>{esc(s["code"])} {esc(s["name"])} <span class="set-year">{s["year"]}</span></li>'
                                 for s in e["japanese_sets"])
            jp = f"""
        <h3>Japanese sets in our collection</h3>
        <ul class="set-list">
{jp_items}
        </ul>"""
        stock = [p for p in products if infos[p["id"]]["era"] == e["id"] and not p.get("sold")]
        if stock:
            names = [f'{p["name"]} {p["grade"]}' for p in stock]
            label = lambda p, n: n + (f' ({infos[p["id"]]["set_short"]})' if names.count(n) > 1 else "")
            links = ", ".join(f'<a href="card-{p["id"]}.html">{esc(label(p, n))}</a>' for p, n in zip(stock, names))
            more = (f' <a href="{era_pages[e["id"]]["file"]}">All {esc(e.get("short", e["name"]))} graded cards →</a>'
                    if e["id"] in era_pages else "")
            stock_html = f'<p class="set-guide-stock"><strong>In stock:</strong> {links}.{more}</p>'
        else:
            stock_html = ('<p class="set-guide-stock">Nothing from this era in stock right now. '
                          '<a href="notify.html">Get new-card alerts</a>.</p>')
        sections.append(f"""      <section class="set-era" id="era-{e['id']}" aria-labelledby="era-{e['id']}-heading">
        <h2 id="era-{e['id']}-heading">{esc(e['name'])} <span class="set-year">{esc(e['years'])}</span></h2>
        <p>{esc(e['summary'])}</p>
        <h3>English sets in release order</h3>
        <ol class="set-list">
{sets}
        </ol>{jp}
        {stock_html}
      </section>""")
    main = f"""<main id="main">
    <div class="container">
      <p class="pdp-breadcrumb"><a href="index.html">Home</a> / <span>Pokémon TCG sets in order</span></p>
    </div>
    <section class="page-hero">
      <h1>Pokémon TCG Sets in Order</h1>
      <p>Every English Pokémon Trading Card Game set from Base Set (1999) to {esc(newest)} ({newest_year}), era by era, with the graded cards we have in stock from each.</p>
    </section>

    <section class="prose set-guide">
      <nav class="set-guide-toc" aria-label="Eras">
        <h2>Jump to an era</h2>
        <ul>
{toc}
        </ul>
      </nav>

{chr(10).join(sections)}

      <p class="set-guide-note">Set list last reviewed {esc(L.load_json('seo/sets.json').get('last_reviewed', ''))}. Dates are English release years; Japanese sets usually release a few months earlier.</p>
    </section>

"""
    return f"{GENERATED_MARK}: set guide from seo/sets.json. Edit that file, not this one. -->\n" + doc + main + bottom


# ---------------------------------------------------------------- shared link blocks

def browse_block(pages):
    groups = [
        ("By grader and grade", [pg for pg in pages if pg["kind"] == "fixed" and pg["id"] in ("psa", "psa-10", "ace")]),
        ("By era", [pg for pg in pages if pg["kind"] == "era"]),
        ("By Pokémon", [pg for pg in pages if pg["kind"] == "pokemon" or pg["id"] == "eeveelutions"]),
        ("By language", [pg for pg in pages if pg["id"] in ("japanese", "english")]),
    ]
    cols = []
    for heading, items in groups:
        if not items:
            continue
        lis = "\n".join(f'            <li><a href="{pg["file"]}">{esc(pg["link_text"][0].upper() + pg["link_text"][1:])}</a></li>'
                        for pg in items)
        cols.append(f"""        <div class="browse-group">
          <h3>{esc(heading)}</h3>
          <ul class="browse-list">
{lis}
          </ul>
        </div>""")
    return f"""<!-- seo:browse -->
    <section class="section container browse-section" aria-labelledby="browse-heading">
      <h2 id="browse-heading" class="section-title">Shop Graded Pokémon Cards</h2>
      <p class="lede">Buy PSA and ACE graded Pokémon cards in the UK by grader, era, Pokémon or language.</p>
      <div class="browse-groups">
{chr(10).join(cols)}
      </div>
      <p class="browse-guide"><a href="{GUIDE_FILE}">Pokémon TCG sets in order, from Base Set to today →</a></p>
    </section>
    <!-- /seo:browse -->"""


def footer_block(pages):
    wanted = ["psa", "psa-10", "ace", "japanese", "english"]
    by_id = {pg["id"]: pg for pg in pages}
    items = [(by_id[k]["file"], by_id[k]["link_text"].replace(" Pokémon", "")) for k in wanted if k in by_id]
    items.append((GUIDE_FILE, "Pokémon sets in order"))
    lis = "".join(f'<li><a href="{f}">{esc(t[0].upper() + t[1:])}</a></li>' for f, t in items)
    return (f'<!-- seo:footer-links --><nav class="footer-shop" aria-label="Shop by category">'
            f'<ul class="footer-links">{lis}</ul></nav>'
            f'<p class="footer-trader">{esc(TRADER)}</p><!-- /seo:footer-links -->')


def fill_markers(files, name, block):
    pattern = re.compile(r"<!-- seo:%s -->[\s\S]*?<!-- /seo:%s -->" % (name, name))
    for rel in files:
        doc = read(rel)
        if pattern.search(doc):
            write(rel, pattern.sub(lambda _m: block, doc, count=1))


# ---------------------------------------------------------------- sitemap and feed

def write_sitemap(products, pages):
    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
             '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">']
    for page in STATIC_PAGES + [pg["file"] for pg in pages] + [GUIDE_FILE]:
        lines.append(f"  <url><loc>{SITE}/{page}</loc></url>")
    for p in products:
        lines += ["  <url>", f"    <loc>{SITE}/card-{p['id']}.html</loc>", "    <image:image>",
                  f"      <image:loc>{SITE}/{p['image']}</image:loc>", "    </image:image>", "  </url>"]
    lines.append("</urlset>")
    write("sitemap.xml", "\n".join(lines) + "\n")


def write_merchant_feed(products, infos, registry):
    items = []
    for p in products:
        if p.get("sold"):
            continue
        i = infos[p["id"]]
        title = L.seo_title(p, i).replace(f" | {STORE}", "")[:150]
        product_type = " > ".join(x for x in ["Graded Pokémon Cards",
                                              registry.era_label(i["era"]) if i["era"] else None,
                                              i["set_rec"]["name"] if i["set_rec"] else None] if x)
        desc = (f"{p['name']} from {i['set_display']} ({i['lang_name']}), card #{p['cardNumber']}"
                f"{', ' + i['rarity'] if i['rarity'] else ''}, graded {p['grade']} {p['gradeLabel']} by {i['company']}. "
                f"{i['company']} cert #{p['certNumber']} can be verified on the grader's website. Sent from the UK with "
                "tracked, signed-for delivery under a numbered tamper-evident seal. 14-day returns.")
        items.append(f"""    <item>
      <g:id>{esc(p['id'])}</g:id>
      <g:title>{esc(title)}</g:title>
      <g:description>{esc(desc)}</g:description>
      <g:link>{SITE}/card-{p['id']}.html</g:link>
      <g:image_link>{SITE}/{p['image']}</g:image_link>
      <g:availability>in_stock</g:availability>
      <g:price>{p['price']:.2f} {p.get('currency', 'GBP')}</g:price>
      <g:condition>used</g:condition>
      <g:brand>Pokémon</g:brand>
      <g:identifier_exists>no</g:identifier_exists>
      <g:product_type>{esc(product_type)}</g:product_type>
      <g:shipping>
        <g:country>GB</g:country>
        <g:service>Tracked, signed-for</g:service>
        <g:price>{SHIPPING_GBP} GBP</g:price>
      </g:shipping>
      <g:min_handling_time>1</g:min_handling_time>
      <g:max_handling_time>2</g:max_handling_time>
    </item>""")
    feed = ('<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0" xmlns:g="http://base.google.com/ns/1.0">\n  <channel>\n'
            f"    <title>{STORE}</title>\n    <link>{SITE}/</link>\n"
            "    <description>PSA and ACE graded Pokémon cards from the UK.</description>\n"
            + "\n".join(items) + "\n  </channel>\n</rss>\n")
    write("google-merchant-feed.xml", feed)


# ---------------------------------------------------------------- main

def main():
    products = load_products()
    registry = L.Registry()
    infos = {p["id"]: L.enrich(p, registry) for p in products}
    unmatched = [p for p in products if not infos[p["id"]]["set_rec"]]
    for p in unmatched:
        print(f"WARNING: '{p['id']}' set '{p['set']}' is not in seo/sets.json. Add the set (or an alias) so it gets an era.")

    pages = L.build_categories(products, infos, registry)
    template = read("product.html")
    ids = []
    for p in products:
        if not re.fullmatch(r"[a-z0-9-]+", p["id"]):
            sys.exit(f"Unsafe product id for a file name: {p['id']!r}")
        image_rel = share_image(p)
        write(f"card-{p['id']}.html", card_page(template, p, infos[p["id"]], image_rel, registry, pages))
        ids.append(p["id"])
    for pg in pages:
        write(pg["file"], category_page(pg, infos, pages))
    write(GUIDE_FILE, guide_page(registry, products, infos, pages))

    # Remove generated pages and images that no longer apply (sold-through categories, removed cards).
    keep = {f"card-{i}.html" for i in ids} | {pg["file"] for pg in pages} | {GUIDE_FILE}
    for name in os.listdir(ROOT):
        if name.endswith(".html") and name not in keep:
            with open(os.path.join(ROOT, name), encoding="utf-8") as f:
                if f.read(len(GENERATED_MARK)) == GENERATED_MARK:
                    os.remove(os.path.join(ROOT, name))
    for name in os.listdir(SHARE_DIR):
        if name.endswith(".jpg") and name[:-4] not in ids:
            os.remove(os.path.join(SHARE_DIR, name))

    html_files = sorted(n for n in os.listdir(ROOT) if n.endswith(".html"))
    fill_markers(html_files, "browse", browse_block(pages))
    fill_markers(html_files, "footer-links", footer_block(pages))

    write("card-pages.js",
          "// Generated by tools/build_card_pages.py. Cards that have their own shareable page.\n"
          f"window.GC01_CARD_PAGES = {json.dumps(sorted(ids))};\n"
          "window.gc01ProductUrl = function (id) {\n"
          "  return window.GC01_CARD_PAGES.indexOf(id) !== -1 ? \"card-\" + id + \".html\" : \"product.html?id=\" + encodeURIComponent(id);\n"
          "};\n")
    write_sitemap(products, pages)
    write_merchant_feed(products, infos, registry)
    print(f"Built {len(ids)} card pages, {len(pages)} category pages, the set guide, sitemap.xml and the Merchant feed.")
    if unmatched:
        print(f"{len(unmatched)} card(s) need their set added to seo/sets.json (see warnings above).")


if __name__ == "__main__":
    main()
